#!/bin/sh

echo "Running Go Linter..."

golangci-lint run ./...
status=$?

if [ $status -ne 0 ]; then
  echo "Linting failed. Please fix the issues before committing!"
  exit 1
else
  echo "Linting passed. Proceeding with commit."
fi
