services:
  server_app:
    build:
      context: ./server
    image: szymonpawelfortuna/zad5-server_app:latest
    ports:
      - "8080:8080"
    networks:
      - app-network

  client_app:
    build:
      context: ./client
    image: szymonpawelfortuna/zad5-client_app:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge