name: Build with Docker Compose & Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and tag Docker images via docker compose
        run: |
          cd zad5
          docker-compose build
          docker tag szymonpawelfortuna/zad5-server_app:latest szymonpawelfortuna/backend:latest
          docker tag szymonpawelfortuna/zad5-client_app:latest szymonpawelfortuna/frontend:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push szymonpawelfortuna/backend:latest
          docker push szymonpawelfortuna/frontend:latest

      - name: Deploy backend container to Azure
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          images: 'szymonpawelfortuna/backend:latest'

      - name: Deploy frontend container to Azure
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          images: 'szymonpawelfortuna/frontend:latest'

       - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.wp.pl
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions - Build ${{ job.status }} for ${{ github.repository }}
          body: |
            The GitHub Actions build finished with status: **${{ job.status }}**
            Repo: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
          to: fortunaszymon@wp.pl
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>