name: Build with Docker Compose & Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker images via docker-compose
        run: |
          cd zad5
          docker-compose build
          docker tag zad5-server_app szymonpawelfortuna/backend:latest
          docker tag zad5-client_app szymonpawelfortuna/frontend:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push szymonpawelfortuna/backend:latest
          docker push szymonpawelfortuna/frontend:latest

      - name: Deploy backend container to Azure
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          images: 'szymonpawelfortuna/backend:latest'

      - name: Deploy frontend container to Azure
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          images: 'szymonpawelfortuna/frontend:latest'
