name: Build and Notify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build backend
        run: |
          cd zad5/server
          go build -o app .

      - name: Build frontend
        run: |
          cd zad5/client
          npm install
          npm run build

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.wp.pl
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions - Build ${{ job.status }} for ${{ github.repository }}
          body: |
            The GitHub Actions build finished with status: **${{ job.status }}**
            Repo: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
          to: fortunaszymon@wp.pl
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
